### ISSUE TITLE
potplayer@210929: Hash check failed

### ISSUE THREAD

**Issue by 7sDream** [Ash258/Shovel-Ash258#323]
Hash check failed!
App:         Ash258/potplayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/210929/PotPlayerSetup64.exe#/cosi.7z
First bytes: 77 90 144 0 3 0 0 0
Expected:    bad518d205646a1a31f911e1690e4d855b90c6447acd8e8215653cf5daf38dd5
Actual:      6d2e986faa23c2f16e4ea731bff2b34ce1acc8d89a54b663f2f04cc3a407b6d4

**Comment by Ash258** [comment]
Do not use my PotPlayer manifest
