### ISSUE TITLE
oh-my-posh strange version error message

### ISSUE THREAD

**Issue by digrouz** [Ash258/Shovel-Ash258#345]
Hello,

I'm using your oh-my-posh manifest with shovel and I get the following error:
        > shovel status
        Scoop is up to date
        ConvertFrom-Json : Primitive JSON non valide : version.
        Au caractère D:\users\digrouz\scoop\apps\scoop\current\lib\manifest.ps1:40 : 27
        + ...   $result = ConvertFrom-Json -InputObject $content -ErrorAction 'Stop ...
        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
            + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
        
        These application manifests have been removed:
            oh-my-posh

Any idea why ? and how to fix it ?

**Comment by Ash258** [comment]
`shovel uninstall oh-my-posh && shovel install main/oh-my-posh`
