### ISSUE TITLE
oh-my-posh@7.6.0: Hash check failed

### ISSUE THREAD

**Issue by IsaacWangTT** [Ash258/Shovel-Ash258#356]
Hash check failed!
App:         Ash258/oh-my-posh
URL:         https://raw.githubusercontent.com/Ash258/Scoop-Ash258/main/support/oh-my-posh/Ash258.yml
First bytes: 35 32 121 97 109 108 45 108
Expected:    766d4cc72ea4334a78eb546bf16310c487246f49566b4d83f457ea587da46706
Actual:      bbd351facd4d90016d993967fa3c289feb5a481602e7fc498b51455e6ec7d644

**Comment by Ash258** [comment]
Do not use my version of oh-my-posh
