### ISSUE TITLE
Question: Constant problems with hash checks. Is there a regular way to get rid of it? 

### ISSUE THREAD

**Issue by thingumajig** [Ash258/Shovel-Ash258#389]
Maybe this is described somewhere, I missed it. What is the right workaround to fix the hash problem with programs like QuickCpu, TaskManagerDeluxe? Thanks.

**Comment by Ash258** [comment]
No

**Comment by thingumajig** [comment]
Can I manually fix the manifest in my local copy of the bucket?

**Comment by Ash258** [comment]
Do whatever you want with your loal file system

**Comment by thingumajig** [comment]
> Do whatever you want with your loal file system
Thanks.
I don't really understand the problem yet. Why are hashes different at all...
